### ISSUE TITLE
No mention of NuGet?

### ISSUE THREAD

**Issue by DylanCh** [IBM-Bluemix-Docs/ComposeForMongoDB#1]
Just saying. If you're going to mention the driver installer, why not provide a better installation option: [from NuGet ](https://www.nuget.org/packages/MongoDB.Driver/)

**Comment by codepope** [comment]
This is a node.js example and the .net driver is not appropriate. 

If you would like to provide a .Net version of the example which deploys on the IBM Cloud, we will gladly accept a pull request.

**Comment by codepope** [comment]
Hi,

We preferred to note how to install without package managers (as for most referenced drivers) but we will consider adding Nuget on the next revision.

I noticed you picked up on nav errors which crept in during a recent revision to the docs. We'll be addressing those in the next update.
